apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: golden-path-templates
spec:
  targets:
    - ./java-templates/springboot-java25-microservice/template.yaml
    - ./java-templates/java25-code-githubactions/template.yaml
    - ./java-templates/gcp-cloudfunction-java-template/template.yaml
    - ./nodejs-templates/node-app/template.yaml
    - ./database/postgres-liquibase-template/template.yaml
    - ./argocd-template/gitops-nonprod/template.yaml
    - ./argocd-template/gitops-prod/prod/template.yaml
