apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.repoName }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/${{ values.repoOwner }}/${{ values.repoName }}.git
    targetRevision: HEAD
    path: helm
    helm:
      values: |
        image:
          repository: ${{ values.imageRegistry }}/${{ values.repoName }}
          tag: latest
        database:
          existingSecret: ${{ values.repoName }}-db
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
