apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java25-code-githubactions
  title: Java 25 Code GitHub Actions Template
  description: Create a Java 25 service repository in GitHub with GitHub Actions
  tags:
    - java
    - githubactions
    - sonarqube
spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Repository Details
      required:
        - repoOwner
        - repoName
        - JiraNumber
        - owner
      properties:
        repoOwner:
          title: Repository Owner
          type: string
          description: GitHub organization or username
          default: devops-champ
          ui:autofocus: true

        repoName:
          title: Repository Name
          type: string
          description: Name of the GitHub repository (lowercase recommended)

        JiraNumber:
          title: Jira Number
          type: string
          description: Mention the jira number

        owner:
          title: Team Owner
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        copyWithoutTemplating:
        - .github/workflows/*
        values:
          repoOwner: ${{ parameters.repoOwner }}
          JiraNumber: ${{ parameters.JiraNumber }}
          repoName: ${{ parameters.repoName | lower }}
          
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName | lower }}
        defaultBranch: main
        repoVisibility: public

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
 
    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - user:default/guest
        title: "Template executed"
        info: "Java 25 repository has been created successfully"
        severity: normal

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Sonar Dashboard
        url: https://sonarcloud.io/project/overview?id=${{ parameters.repoName }}
      - title: GitHub Actions
        url: https://github.com/${{ parameters.repoOwner }}/${{ parameters.repoName }}/actions/workflows/ci.yml
