apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: Sample service with CI/CD
  annotations:
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: devops-champ_${{ values.repoName }}
    jenkins.io/job-full-name: devops-champ/${{ values.repoName }}/main
    roadie-backstage-pull-requests/default-filter: "is:open is:pr"
    platform.io/argocd-dev: guestbook-dev
    platform.io/argocd-qa: guestbook-qa
    platform.io/argocd-prod: guestbook-prod
    platform.io/jira: ${{ values.JiraNumber }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  dependsOn:
    - resource:default/orders-db
    - resource:default/kafka-cluster
