apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: Sample service with CI/CD
  annotations:
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: devops-champ_${{ values.repoName }}
    jenkins.io/job-full-name: devops-champ/${{ values.repoName }}/main
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
  dependsOn:
    - component:default/payment-service
    - component:default/user-service
    - resource:default/orders-db
    - resource:default/kafka-cluster
