apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: Sample service with CI/CD
  annotations:
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: devops-champ_${{ values.repoName }}
    argocd/app-name: guestbook #devops-champ_${{ values.repoName }}
    roadie-backstage-pull-requests/default-filter: "is:open is:pr"
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
  dependsOn:
    - component:default/payment-service
    - component:default/user-service
    - resource:default/orders-db
    - resource:default/kafka-cluster
