apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: Sample service with CI/CD
  annotations:
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: devops-champ_${{ values.repoName }}
    roadie-backstage-pull-requests/default-filter: "is:open is:pr"
    platform.io/argocd-dev: ${{ values.repoName }}-dev
    platform.io/argocd-qa: ${{ values.repoName }}-qa
    platform.io/argocd-prod: ${{ values.repoName }}-prod
    grafana/host-id: default
    grafana/dashboard-selector: folder=Shared with me
    grafana/alert-label-selector: service=my-service
    grafana/tag-selector: 'my-tag'
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
  dependsOn:
    - resource:default/orders-db
    - resource:default/kafka-cluster
