apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.repoName }}-${{ values.environment }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/${{ values.repoOwner }}/${{ values.repoName }}.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - ../../values/${{ values.repoName }}/values-${{ values.environment }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.repoName }}-${{ values.environment }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
